### ISSUE TITLE
Where is crate docs?

### ISSUE THREAD

**Issue by nikitavoloboev** [helix-editor/nucleo#3]
Tried looking in readme [and crates.io](https://crates.io/search?q=nucleo) but didn't find it.

Want to use this crate in my project. :)

Thank you.

**Comment by the-mikedavis** [comment]
Nucleo isn't published to crates.io yet: Pascal will publish a release once it's ready for Helix, see https://github.com/helix-editor/helix/pull/7814#discussion_r1285012830. To use nucleo you will need to add it [as a git dependency](https://github.com/helix-editor/helix/blob/89061b87d9ac7803ddfa79d33b9c139a9b8f56f5/helix-core/Cargo.toml#L51) for now and build docs locally with `cargo doc`.
