### ISSUE TITLE
Handling of Japanese keyboard 'Ideographic Space'

### ISSUE THREAD

**Issue by alexrutar** [helix-editor/nucleo#64]
On most Japanese keyboards, pressing 'Space' does not input usual ASCII space `' '` but rather the 'Ideographic Space' character `\u{3000}`. Therefore if you are using the fuzzy picker with a Japanese keyboard, the prompt splitting is done incorrectly. When using a search interface it is usually expected that the splitting will occur on 'Ideographic Space'.

This would be very easy to handle if desired. More generally, would it be sensible to split instead based on the Unicode whitespace property? I.e. something like
```rust
fn pattern_atoms(pattern: &str) -> impl Iterator<Item = &str> + '_ {
    let mut saw_backslash = false;
    pattern.split(move |c| {
        saw_backslash = match c {
            ch if !saw_backslash && ch.is_whitespace() => return true,
            '\\' => true,
            _ => false,
        };
        false
    })
}
```
Or of course the solution just for `\u{3000}` like
```rust
fn pattern_atoms(pattern: &str) -> impl Iterator<Item = &str> + '_ {
    let mut saw_backslash = false;
    pattern.split(move |c| {
        saw_backslash = match c {
            ' ' | '\u{3000}' if !saw_backslash => return true,
            '\\' => true,
            _ => false,
        };
        false
    })
}
```

**Comment by pascalkuthe** [comment]
switching to `ch.is_whitespace()` makes sense to me :+1:
